FROM golang:1.17 AS src

WORKDIR /go/src/app/
# Download dependencies so that they are cached by docker
COPY go.mod ./
COPY go.sum ./
RUN go mod tidy

COPY . ./

# Build Go Binary
RUN set -ex; \
    CGO_ENABLED=0 GOOS=linux go build -ldflags="-w -s" -o ./{{ .Name }} ./cmd/{{ .Name }}/main.go;

FROM alpine
LABEL MAINTAINER Maintainer-Name <author@example.com>

# Add new user 'appuser'. App should be run without root privileges as a security measure
RUN adduser --home "/home/appuser" --disabled-password appuser --gecos "appuser,-,-,-"
USER appuser
RUN mkdir -p /home/appuser/app
WORKDIR /home/appuser/app/

COPY --from=src /go/src/app/{{ .Name }} .
COPY .env .env

EXPOSE {{ .Port }}

# Run Go Binary
CMD /home/appuser/app/{{ .Name }}