FROM golang:1.16-alpine AS src

WORKDIR /go/src/app/
COPY . ./

# Build Go Binary
RUN set -ex; \
    CGO_ENABLED=0 GOOS=linux go build -ldflags="-w -s" -o ./server ./cmd/go8/main.go;

FROM alpine
LABEL MAINTAINER Hafiz <author@example.com>

# Add new user 'appuser'. App should be run without root privileges as a security measure
RUN adduser --home "/home/appuser" --disabled-password appuser --gecos "appuser,-,-,-"
USER appuser
RUN mkdir -p /home/appuser/app
WORKDIR /home/appuser/app/

COPY --from=src /go/src/app/server .
COPY .env .env

EXPOSE {{ .Port }}

# Run Go Binary
CMD /home/appuser/app/server